language: viml

install:
  - hg clone https://code.google.com/p/vim/ /tmp/vim
  - (cd /tmp/vim && ./configure && make && sudo make install)
  - git clone https://github.com/thinca/vim-themis /tmp/themis

script:
  - vim --cmd version --cmd quit
  - /tmp/themis/bin/themis --reporter spec
